### ISSUE TITLE
New Feature: Allow $default to be a callback

### ISSUE THREAD

**Issue by josephlavin** [DusanKasan/Knapsack#48]
Hello,

It would be nice if the `getOrDefault` & `find` methods would execute and return the result of a closure if provided.

```php
return $default instanceof \Closure ? $default() : $default
```

This would allow for code like this:
```php
Collection::from()->getOrDefault('foo', function() {
	return new SomeExpensiveObject();
});

Collection::from()->getOrDefault('foo', function() {
	throw new \Exception('foo is required');
});
```

I would be happy to build & submit a PR if this is a desired feature for this project.

Thank You

**Comment by DusanKasan** [comment]
Hi. GetOrDefault/Find can not be altered in the proposed way because of the conflicts it would cause if the collection in question was a collection of functions. Would you return the passed function or execute it and return the result? 

Do you have a use-case for this? Maybe an introduction of new methods named something like GetOrExecute/GetOrCallback/GetOrDo/etc could be beneficial. Then again, maybe you'll be better off composing existing functionality like: 
```
$item = $collection
    ->get(key, true)
    ->map(function($i){
            return function() {return $i}
    })
    ->append(expensiveCallback)
    ->first()()
```

**Comment by josephlavin** [comment]
A collection of closures... did not think of that :)  The idea is to execute the callback and return in the result.

The primary scenario I have is throwing an exception if the collection does not contain an element. Something like this:
```php
if(!$collection->has('foo')) {
	throw new \Exception('foo is required');
}

return $collection->get('foo');
```
Becomes:
``` php
return $collection->getOrCallback('foo', function() {
	throw new \Exception('foo is required');
});
```

The callback will not be executed unless the default value is returned.

**Comment by DusanKasan** [comment]
Would the solution I proposed (composition of current functionality, see my previous post) work for you? I.e. is it good enough? I feel like introduction of a specialized function would have just semantical value at this point.

**Comment by josephlavin** [comment]
Thanks for the input & feedback and creating this library 👍
